name: check_issue_approval
on:
  issue_comment:
    types: [opened, edited]
    
jobs:
 check-issue:
  runs-on: ubuntu-latest
  if: contains(github.event.comment.body, 'approved')
  steps:
  - name: print package name and version
    #run: echo "$BODY" 
    run: head -2 "$BODY"
  env:
    BODY: ${{ github.event.issue.body }}
