name: pull_jfrog_package
on:
  issues:
    types: [opened, edited]

jobs:
 check_approval:
  runs-on: ubuntu-latest

  steps:
  - name: print body
    run: echo "$BODY"  
  env:
    BODY: ${{ github.event.issue.body }}
  
    name: Get required package
    run: |
      while IFS="" read -r line ||  [ -n "$line" ]
            do
               #echo "Checking file $line for the package and version"
               cat "$BODY" > "$line"
               echo "$line"
            done <"$BODY"   
     



       
      

