name: pull_jfrog_package
on:
  issues:
    types: [opened, edited]
  
  push:
     branches: [ main ]    

  workflow_dispatch: 
 
jobs:
   issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $COMMENT
        env:
          COMMENT: ${{ github.event.comment.body }}

       
      

