name: check_issue_approval
on:
  issue_comment:
    types: [opened, edited]
env:
    BODY: ${{ github.event.issue.body }}
jobs:
 check_issue_approval:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/approve')
    outputs: 
      approved: ${{ steps.check-approval.outputs.approved }}
    steps:
      - name: Check required package
        run: |
           VAR=$(echo $BODY | grep -EoP '\w\@\d\.\d\.\d')
           echo $VAR
    
 
