name: check_issue_approval
on:
  issue_comment:
    types: [opened, edited]
    
jobs:
 check-issue:
  runs-on: ubuntu-latest
  if: contains(github.event.comment.body, 'approved')
  steps:
  - name: print body
    #run: echo "$BODY" 
    run: cat "$BODY" | head -2 | tail -1
  env:
    BODY: ${{ github.event.issue.body }}
