name: pull_jfrog_package
on:
  issues:
    types: [opened, edited]
  issue_comment:
   - run: echo ${{ github.event.comment.body }}
   - run: echo ${{ github.event.changes.body.from }}

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}


       
      

