name: check_issue_approval
on:
  issue_comment:
    types: [opened, edited]
    
jobs:
 check-issue:
  runs-on: ubuntu-latest
  if: contains(github.event.comment.body, 'approved')
  steps:
   - name: read issue body
#     run: echo "$BODY" 
#  env:
#    BODY: ${{ github.event.issue.body }}
   - uses: peter-murray/issue-body-parser-action@v2
   - name: Parse Issue Body
     if : steps.issue_body_parser_request.outputs.payload != 'Name'
     id: issue_body_parser
     env:
         VERSION: ${{ fromJson(steps.issue_body_parser_request.outputs.payload).version }}
     run: |
        echo $VERSION

    
 
