name: check_issue_approval
on:
  issue_comment:
    types: [opened, edited]
    
jobs:
 check-issue:
  runs-on: ubuntu-latest
  if: contains(github.event.comment.body, 'approved')
  steps:
#   - name: read issue body
#     run: echo "$BODY" 
#  env:
#    BODY: ${{ github.event.issue.body }}

   - name: Parse Issue Body
     uses: peter-murray/issue-body-parser-action@v1
     id: issue_body_parser
     with:
       github_token: ${{ secrets.GH_TOKEN }}
       issue_id: ${{ github.event.issue.number }}
       payload_marker: target_payload
    
 
