name: pull_jfrog_package
on:
  issues:
    types: [opened, edited]
  
  push:
     branches: [ main ]    

  workflow_dispatch:  
env:
  ISSUE_BODY: ${{ github.event.issue.body }}
  ISSUE_COMMENTS: ${{ github.event.comment.body }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  ASSIGNEES_LIST: ${{ join(github.event.issue.assignees.*.login, ',') }}  

jobs:
  check_approval:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
      with:
          ISSUE_BODY: $ISSUE_BODY
          ISSUE_COMMENTS: $ISSUE_COMMENTS
          ISSUE_NUMBER: $ISSUE_NUMBER
          ASSIGNEES_LIST: $ASSIGNEES_LIST
    - name: print body
      run: echo ${{ github.event.comment.body }} 
 # perform_jfrog_pull:
 #     runs-on: ubuntu-latest
      if: contains(github.event.issue.body, '/approve') 
 #     steps:
    - name: Install npm
      uses: actions/setup-node@v3
      with:
         node-version: '16'
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3  
    - name: Check jfrog cli version
      run: jf --version      

