name: pull_jfrog_package
on:
  issues:
    types: [opened, edited]
  
  push:
     branches: [ main ]    

  workflow_dispatch:  

jobs:
  check_approval:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: print body
      run: echo ${{ github.event.comment.body }}
