name: pull_jfrog_package
on:
  issue_comment:
    types: [opened, edited]

  workflow_dispatch: 

jobs:
 print:
  runs-on: ubuntu-latest
  if: contains(github.event.comment.body, 'approved')	
  steps:
  - name: print body
    run: echo "$BODY"  
  env:
    BODY: ${{ github.event.issue.body }}
     



       
      

