name: pull_jfrog_package
on:
  issue_comment:
    types: [opened, edited]

  workflow_dispatch: 

jobs:
 dump:
  runs-on: ubuntu-latest
  steps:
  - name: $github
    run:   echo "$GITHUB_CONTEXT"
    env:
     GITHUB_CONTEXT: ${{ toJson(github) }}


       
      

