name: pull_jfrog_package
on:
  issue_comment:
    types: [opened, edited]

  workflow_dispatch: 

jobs:
 print:
  runs-on: ubuntu-latest
  steps:
  - name: print body
    run: echo "$BODY"  
  env:
    BODY: ${{ github.event.comment.body }}



       
      

