name: pull_jfrog_package
on:
  issue_comment:
    types: [opened, edited]

jobs:
 check_approval:
  runs-on: ubuntu-latest

  steps:
  - name: print body
    run: echo "$BODY"  
  env:
    BODY: ${{ github.event.issue.body }}
     



       
      

